### ISSUE TITLE
Documentation on Image-based installation is wrong

### ISSUE THREAD

**Issue by codebude** [mqtt-tools/mqttwarn#670]
The documentation on Docker/OCI ( https://mqttwarn.readthedocs.io/en/latest/usage/oci.html ) states that there are two images available:
```
# The standard image on GHCR.
export IMAGE=ghcr.io/mqtt-tools/mqttwarn-standard:latest

# The full image on GHCR.
export IMAGE=ghcr.io/mqtt-tools/mqttwarn-full:latest
```

Trying to use one of these ends up in:
`Error response from daemon: manifest unknown` 

Actually there are no images with the tag `latest`. I suggest to either update the documentation (use `nightly` instead of `latest` tag) or push also the `latest` to GHCR.

**Comment by amotl** [comment]
Hi Raffael,

thanks for reporting this flaw. Indeed, you are right. We only recently migrated from `jpmens` to `mqtt-tools`, and did not run another release yet, in order to populate the OCI images to GHCR appropriately. Thanks a stack for the reminder, we will do that soon.

In the meanwhile, please use `jpmens`, where in the future, after the next release, `mqtt-tools` should be used, and how the documentation describes it.

Despite that the repository has ceased to exist at that location, the images are still around [^1][^2], and there, you will also find corresponding `latest` variants.

With kind regards,
Andreas.

[^1]: `docker pull ghcr.io/jpmens/mqttwarn-standard:latest`
[^2]: `docker pull ghcr.io/jpmens/mqttwarn-full:latest`

**Comment by codebude** [comment]
Thanks for clarification! Container is up, running and my first UDF does it's job. :-)

**Comment by amotl** [comment]
Hi again,

mqttwarn 0.34.1 has been released [^1], in order to populate the OCI image space ("package", in GH's parlance) [^2][^3] correctly, in order to make reality match the documentation.

![image](https://github.com/mqtt-tools/mqttwarn/assets/453543/aec114ea-c888-453e-a047-9c1521476d5f)

> Container is up, running and my first UDF does it's job. :-)

Excellent. If you think your recipe could be helpful for others, feel free to share it back with us so we could bring it into the [examples](https://github.com/mqtt-tools/mqttwarn/tree/main/examples) folder.

With kind regards,
Andreas.

[^1]: https://github.com/mqtt-tools/mqttwarn/releases/tag/0.34.1
[^2]: https://github.com/mqtt-tools/mqttwarn/pkgs/container/mqttwarn-standard
[^3]: https://github.com/mqtt-tools/mqttwarn/pkgs/container/mqttwarn-full
