### ISSUE TITLE
[ntfy] Error if message contains newline character `\n`

### ISSUE THREAD

**Issue by zoic21** [mqtt-tools/mqttwarn#677]
Hello,

I got a weird issue, if message contain a return line a got this error : 

`requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: '=?utf-8?q?Fin_de_l=27arrosage_de_la_zone_2=2C_humidit=C3=A9_du_sol_=3A_13_?=\n =?utf-8?q?=25?='`

I think it's due to `\n` in my message, maybe you can just remove it when you parse ?

Thank in advance

**Comment by jpmens** [comment]
Is there a specific reason why you can't remove it before submission? ;-)

**Comment by zoic21** [comment]
Yes and no, it's send by esphome and he add this, I need to find why, it's a bug (on my code I think) but maybe you can handle this type of case.

**Comment by amotl** [comment]
Dear Loïc,

thank you for writing in.

While I've not investigated further yet, I discovered the [TestServer_PublishMessageInHeaderWithNewlines](https://github.com/binwiederhier/ntfy/blob/b222541ea864b10652cf0de02a0bbc30214c9f10/server/server_test.go#L607-L616) function in ntfy's test suite. It may indicate your use case should work well, even when using newlines in the message body, and the header transport style for communications, which mqttwarn is using.

Maybe the problem is indeed on mqttwarn's behalf?

With kind regards,
Andreas.

/cc @binwiederhier

**Comment by codebude** [comment]
From my understanding linebreaks are not allowed in HTTP headers. They are defined as header separators in the RFC and can't be send in header content: https://stackoverflow.com/a/47422593/251719

I see two options: 
1) Either strip all linebreaks (e.g. via `re.sub("\r?\n", "", data)` ) from the message, before pasing it to the Header/encode function: https://github.com/mqtt-tools/mqttwarn/blob/main/mqttwarn/services/ntfy.py#L242
2) Change the way, the ntfy service is implemented and post the message either as HTTP body (https://docs.ntfy.sh/publish/) or just send all properties incl. body as JSON (https://docs.ntfy.sh/publish/#publish-as-json).

Personally I would suggest to go with the second option, because I think it is legit to have linebreaks in notification messages. Thus option 1 seems more like a suboptimal workaround.

**Comment by codebude** [comment]
Hm maybe there's one downside with the JSON method. As far as I read the documentation correctly, attachments can only be sent out as links. Not directly sent (as mqttwarn does with the actual implementation). So maybe we should open an issue at ntfy.sh first and ask them, to enable file/attachments via the JSON endpoint. (e.g. as base64 encoded JSON property).

**Comment by codebude** [comment]
I just opened an enhancement request at ntfy that asks for attachment/file support in the publish via JSON endpoint: https://github.com/binwiederhier/ntfy/issues/762

**Comment by codebude** [comment]
@amotl I got feedback on the request at ntfy and it's not planned to accept attachments in JSON. 
So maybe the best workaround then would look like:

- Take the current implementation but send the message as body instead of header. (That should enable line breaks)
- If it's a message with attachment and no explicit message, then send it as today (attachment in body, everything else as headers)
- if it's a message with attachment and message, then replace all \n in the message and send attachment as body and message as header

**Comment by amotl** [comment]
Hi Raffael, thanks a stack for reaching out to ntfy, and for coming back with your proposal. I think it is a reasonable approach to resolve this issue. Cheers, Andreas.

On 3 June 2023 18:42:44 CEST, Raffael Herrmann ***@***.***> wrote:
>@amotl I got feedback on the request at ntfy and it's not planned to accept attachments in JSON. 
>So maybe the best workaround then would look like:
>
>- Take the current implementation but send the message as body instead of header. (That should enable line breaks)
>- If it's a message with attachment and no explicit message, then send it as today (attachment in body, everything else as headers)
>- if it's a message with attachment and message, then replace all \n in the message and send attachment as body and message as header
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mqtt-tools/mqttwarn/issues/677#issuecomment-1575060446
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

**Comment by amotl** [comment]
Hi again,

GH-684 intends to implement your suggestion, @codebude. Thank you very much.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

I've not tracked this in detail, but also didn't hear about any complaints. Do you think this issue can be considered resolved?

With kind regards,
Andreas.

**Comment by codebude** [comment]
So far, everything seems to be working as expected. Thanks again for the implementation :-)

**Comment by amotl** [comment]
Excellent, thank you. Let us know if you observe any other issues on this or related topics.
